### ISSUE TITLE
aliases?

### ISSUE THREAD

**Issue by benman1** [catherinedevlin/ipython-sql#77] opened 2017-02-28 13:29 UTC
Hi, 
 this could be potentially very useful - thanks for the work on this. However, I can't use alias, such as in

`select client_id as user from clients;`

or

`select client_id from clients c;`

Especially the second usage is very important for nesting queries or anything involving a one-to-many relationship between tables. 

Is this going to be implemented? Is there a way to do this? 

Cheers!

**Comment by jstoebel** [comment] 2017-07-30 00:55
could not duplicate on sqlite for OS X. By chance has this been fixed?

**Comment by kannes** [comment] 2018-07-10 12:14
Aliases work without any problems for me. Should be closed as non-reproducible as there was no further input by the reporter.

**Comment by benman1** [comment] 2018-07-10 12:44
Should there have been more input from the reporter? Was the question directed to me? ;)

More seriously, I haven't used the library much since then, but when I was it, this was one of the gotchas. It's a nice tool though, and if it works now, or it works for other people, all the better.

**Comment by kannes** [comment] 2018-07-14 20:03
:D

I was just looking through the issues and check which ones are worthy of closing. I used aliases without any problems a lot since finding this great magic. Unless you can still reproduce your issue I guess it is simply a thing of the past.

**Comment by benman1** [comment] 2018-07-15 13:19
:) Fair enough. Thanks for explaining - it's nice to hear it's working.
Good job, Hannes. Go on closing this one then.

**Comment by catherinedevlin** [comment] 2018-07-18 19:53
Thanks for researching this, everybody!  I'll go ahead and close.

**Closed by catherinedevlin** 2018-07-18 19:53 UTC
Labels: can't duplicate
